#!/bin/sh
# generated by ctx v0.3.5 — regenerate with 'ctx harness init'
# ctx:checksum sha256:1e94faa878ff2546fb0012da7874df65dd36a15138443f759ac409a7786fc925
set -u
ctx harness compat --require "0.3.5" >/dev/null 2>&1 || exit 0
cat >/dev/null 2>&1 || true
ctx map --budget 2000 || {
  echo "ctx hooks: ctx map failed; run ctx index to rebuild the index." >&2
  exit 0
}
