#!/bin/sh
# generated by ctx v0.4.0 — regenerate with 'ctx harness init'
# ctx:checksum sha256:f251b3442bc4f4608eba12cd84f3ff622e84021f74f828212d0f2fa8766191c3
set -u
ctx harness compat --require "0.4.0" >/dev/null 2>&1 || exit 0
cat >/dev/null 2>&1 || true
ctx map --budget 2000 || {
  echo "ctx hooks: ctx map failed; run ctx index to rebuild the index." >&2
  exit 0
}
