/// Built-in ignore patterns for files that shouldn't be included in AI context.
pub const DEFAULT_IGNORES: &[&str] = &[
    // Version control
    ".git/",
    ".svn/",
    ".hg/",
    ".bzr/",
    ".darcs/",
    ".husky/",
    // IDE/Editor directories
    ".vscode/",
    ".idea/",
    ".vs/",
    ".vscode-test/",
    ".sublime-project",
    ".sublime-workspace",
    "*.swp",
    "*.swo",
    // Lock files
    "*.lock",
    "*.lockb",
    "package-lock.json",
    "yarn.lock",
    "poetry.lock",
    "Gemfile.lock",
    "pnpm-lock.yaml",
    "bun.lockb",
    "Cargo.lock",
    "Pipfile.lock",
    // Dependencies & build outputs
    "node_modules/",
    "vendor/",
    "Pods/",
    "Carthage/",
    "dist/",
    "build/",
    "out/",
    "target/",
    ".next/",
    ".nuxt/",
    "coverage/",
    ".nyc_output/",
    ".gradle/",
    "gradle/",
    ".m2/",
    ".cargo/",
    // Cache & temporary directories
    ".cache/",
    "cache/",
    "tmp/",
    "temp/",
    ".tmp/",
    ".temp/",
    "*.cache",
    // Build caches & incremental build files
    "*.tsbuildinfo",
    ".eslintcache",
    ".parcel-cache/",
    ".webpack/",
    ".rollup.cache/",
    // Environment files & secrets
    ".env",
    ".env.*",
    ".env.local",
    "secrets/",
    "private/",
    // Test outputs & coverage
    "test-results/",
    "spec-results/",
    ".coverage",
    "htmlcov/",
    // Python environments
    "venv/",
    ".venv/",
    "env/",
    "__pycache__/",
    ".mypy_cache/",
    ".pytest_cache/",
    ".tox/",
    // Document files
    "*.pdf",
    "*.docx",
    "*.doc",
    "*.xls",
    "*.xlsx",
    "*.ppt",
    "*.pptx",
    // Image files
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.bmp",
    "*.tiff",
    "*.ico",
    "*.webp",
    "*.svg",
    // Media files
    "*.mp3",
    "*.mp4",
    "*.avi",
    "*.mov",
    "*.wmv",
    "*.webm",
    "*.m4a",
    "*.m4v",
    // Binary & system files
    "*.so",
    "*.dll",
    "*.dylib",
    "*.lib",
    "*.exe",
    "*.bin",
    // Archives
    "*.tar",
    "*.gz",
    "*.bz2",
    "*.tgz",
    "*.zip",
    "*.rar",
    "*.7z",
    "*.dmg",
    "*.pkg",
    "*.msi",
    "*.deb",
    "*.rpm",
    "*.iso",
    "*.img",
    // Compiled files
    "*.pyc",
    "*.pyo",
    "*.o",
    "*.obj",
    "*.class",
    "*.jar",
    "*.war",
    "*.ear",
    // Data files
    "*.h5",
    "*.hdf5",
    "*.pkl",
    "*.sqlite",
    "*.sqlite3",
    "*.db",
    "*.joblib",
    "*.mat",
    "*.npz",
    "*.npy",
    // Font files
    "*.woff",
    "*.woff2",
    "*.ttf",
    "*.eot",
    "*.otf",
    // Virtual machine files
    "*.vdi",
    "*.vhd",
    "*.vmdk",
    "*.qcow2",
    // Security files
    "*.crt",
    "*.pem",
    "*.key",
    // System files
    ".DS_Store",
    "Thumbs.db",
    "Desktop.ini",
    // Backup and temporary patterns
    "*.tmp",
    "*.temp",
    "*.bak",
    "*.backup",
    "*~",
    "*.orig",
    "*.rej",
    // Documentation directories (often auto-generated)
    "docs/_build/",
    "site/",
    "_site/",
    // Package artifacts
    "*.whl",
    "*.egg-info/",
    "*.egg",
    "*.dist-info/",
    // Memory dumps & profiles
    "*.stackdump",
    "*.dmp",
    "heapdump*",
];
